import React from "react";

import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/libs/providers/ThemeProviders";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['300', '400', '500', '700'],
  variable: "--font-ubuntu"
});

// const ubuntu = localFont({
//   src: "./fonts/Ubuntu-R.woff",
//   variable: "--font-ubuntu-r",
//   weight: "300 400 500 700 800",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntu.variable} font-[family-name:var(--font-ubuntu-r)] antialiased`}
      >
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
}
